services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ds
      POSTGRES_PASSWORD: ds
      POSTGRES_DB: ev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  pgdata:
